### ISSUE TITLE
Bower / Require.js / Grunt / Jasmine / JShint

### ISSUE THREAD

**Issue by ezze** [shashwatak/satellite-js#12]
Hi, Shashwat!

Many thanks for your efforts on bringing this library to JavaScript!

I forked this library and made many changes to meet the requirements fixed for projects in our organization. These changes also affect the naming convention, so probably you will not accept them due to reasons mentioned in your `README.md`. Anyway, [take a look at this](https://github.com/solarpatrol/satellitejs/tree/requirejs), probably you will be interested in having a pull request from me.

First of all, source code is reorganized as [Requirejs AMD modules](http://requirejs.org/) and can be built with [Grunt](http://gruntjs.com/) instead of `Makefile`. This is more JavaScript way! As the result, the library has both minified and non-minified versions. It can be used by accessing global `satellite` object as well as by requiring it as module in Require.js. 

Build script also validates the code with [JSHint](http://jshint.com/). It helped me to make code cleaner, follow [lower camel case naming convention](https://en.wikipedia.org/wiki/CamelCase) and locate all unused variables. They are commented and marked by:

> TODO: defined but never used

I also added the support of running tests written with [Jasmine](http://jasmine.github.io/), and it doesn't depend on browser because [Phantom.js](http://phantomjs.org/) is used. Unfortunatelly, I had no enough time to rewrite all your tests with Jasmine but it should be pretty easy. There is only one `sgp4` test at the moment that checks calculations of satellite's position and velocity.

Another major requirement was to make the library installable with [Bower](http://bower.io) package manager:

    bower install satellitejs

**Comment by shashwatak** [comment]
Definitely very excited about the improvements to testing! That  (and the JSHint stuff) alone is worth a PR =)

I was worried when you said you changed the naming convention, but I see you haven't deviated from Brandon Rhodes original code, so that's all good.

I was also worried about grunt, bower, require, dependencies, but they seem to be much more common and accepted today than when I started this project, much like make and apt-get.

Anyway, I've always been vary of introducing complexity and cruft, but your changes seem to reduce complexity and make it easier to use this library, so I'm all for it! And you kept the README up to date as well! Well done.

Send me a PR and I'll gladly accept =D

**Comment by ezze** [comment]
Hi, man!

Great to hear that you like it! It would be very good if you continue to maintain the library with accepted changes. :)

I created a pull request https://github.com/shashwatak/satellite-js/pull/14.

**Comment by shashwatak** [comment]
Check the README, I made a small addition =)

**Comment by ezze** [comment]
Thank you so much! :)
