### ISSUE TITLE
Some satrecs return false for position/velocity with propagate 

### ISSUE THREAD

**Issue by syntagmatic** [shashwatak/satellite-js#19]
Having trouble with these TLEs for some reason.

```
FLOCK 1B-28             
1 40423U 98067FP  15219.24788283  .05567779  12028-4  14293-2 0  9997
2 40423  51.6133 170.3484 0007348 241.2767 118.7501 16.27910103 34192
MICROMAS                
1 40457U 98067GA  15213.38588329  .08885032  12472-4  72013-3 0  9998
2 40457  51.6142 195.6182 0009646 310.7124  49.3640 16.38908268 33335
```

When I load them, I get `Uncaught TypeError: Cannot read property 'x' of undefined` on line 713

Most TLEs do work though. I'm using the library to create groundtracks with D3.js

http://bl.ocks.org/syntagmatic/6c149c08fc9cde682635
http://bl.ocks.org/syntagmatic/raw/6c149c08fc9cde682635/noaa.html
http://bl.ocks.org/syntagmatic/raw/6c149c08fc9cde682635/cubesat.html
http://bl.ocks.org/syntagmatic/raw/6c149c08fc9cde682635/molniya.html
http://bl.ocks.org/syntagmatic/raw/6c149c08fc9cde682635/gps.html
http://bl.ocks.org/syntagmatic/raw/6c149c08fc9cde682635/intelsat.html

I may go digging into the source to find the error. Some of these examples can also stop working after running for a few minutes, especially Molniya.

Thanks for the awesome library. It took me just an hour or two to get something together, after spending a couple days looking into calculating ground tracks from scratch. I would love to submit some graphical, web-based examples for the library if you're interested.

**Comment by wenzul** [comment]
For example for decaying satellites sgp4 returns `{position: false, velocity: false}`.
You should check `satrec.error` if and to figure out the reason why `position` has no attribute `x`.

Also note, that the TLEs are designed for a precise prediction within maybe two weeks. After that the satellite drifts to far away due to perturbations. Calculating the terms could fail.

**Comment by syntagmatic** [comment]
Ahh, my mistake. The TLE does load into `satrec`, but my application throws the error when converting to geodetic coordinates due to lack of an `x` value.

`satrec.error` returns the integer `1` for problematic TLEs.

I looked at the data in a parallel coordinates view to see which orbital parameters were special for MICROMAS and FLOCK 1B-28. They both appear to have high Mean Motion and First Derivative of Mean Motion.

http://bl.ocks.org/syntagmatic/4446b31c6cd746eedaeb

Perhaps these are problematic for prediction? I'm wondering if there's some threshold to know when prediction by satellite.js isn't possible.

Thanks for the note on TLE prediction accuracy. I'll probably go back to the examples and have them start from the date the data was collected and loop after a week or two. It's mostly a simple example of how to use satellite.js with D3.js, I don't plan to keep the data up-to-date.

**Comment by wenzul** [comment]
For your visualization you can may use weeks. But in that time it also can decay.

> satrec.error contains the integer 1 for problematic TLEs.
`satrec.error` > 0. It's devided into different cases.

**Comment by shashwatak** [comment]
Those visualizations are really cool!

**Comment by wenzul** [comment]
Yes, sorry! They are! :)

**Comment by nhamer** [comment]
I don't think there's actually a bug in the calculations here, calculating near the epoch works fine (FLOCK 1B-28)

console.log(JSON.stringify(satellite.sgp4(satrec, 0).position));
{"x":-6486.244055534791,"y":1103.1672497210636,"z":-0.11404306548681002}

Eccentricity is a function of bstar and time, and when to try to propagate to current time, it's negative.

sgp4 should return { satrec: satrec, position: undefined, velocity: undefined } instead of [false, false] though.

**Comment by terekcampbell** [comment]
Wanted to mention that the returning of [false, false] (after upgrading from 1.3.0 to 2.0.2) is an issue for myself as well

**Comment by thkruz** [comment]
I just wanted to toss out a workaround since regardless of returning undefined or false, you can't plot it. If you use a try/catch function (https://www.w3schools.com/js/js_errors.asp) then it will catch all of the false returns and you either skip that iteration or remove the satellite (99% of my failures are decayed objects that I need to remove from my catalogue).

**Comment by thkruz** [comment]
Closing since it is very stale and was likely an issue with decayed/old TLEs not the actual library.
