### ISSUE TITLE
observerCoordsEcf, velocityEcf not defined

### ISSUE THREAD

**Issue by bdefore** [shashwatak/satellite-js#24]
Example in README references:

`dopplerFactor = satellite.dopplerFactor(observerCoordsEcf, positionEcf, velocityEcf);`

But neither of `observerCoordsEcf` or `velocityEcf` appear to be available.

**Comment by shashwatak** [comment]
Yes, you will have to define those yourself using the functions described in the README.

**Comment by thkruz** [comment]
Recommend using Eci for the dopplerFactor example in the readme. There is no available function to convert velocityEci to velocityEcf and the readme already explains you _can_ use ecf if you have those values.

**Comment by nhamer** [comment]
satellite.eciToEcf converts it

**Comment by ericsvendsen** [comment]
I realize this issue thread is really old, but thought I would post my solution here for calculating ECF velocity in case others have the same question. If accuracy is vital and you're able to track down and decipher the math mentioned above, then great! I was not though, and this seemed to worked out pretty well for me. :)

Basically, you can determine ecf velocity using the eci data that satellite.js provides via the `propagate` or `sgp4` methods (Note: I'm using dayjs elsewhere in my project, so that's why I'm using it here in this example. It is certainly not required)
```
const now = dayjs(); // date/time right now
const pv = propagate(satrec, now.toDate()); // eci position and velocity for a given satrec
if (pv.position && pv.velocity) {
    const ecfPosition = eciToEcf(pv.position, gstime(now.toDate())); // convert eci position to ecf
    const ecfMoved = eciToEcf( // add eci velocity to eci position, and convert the result to ecf
        {
            x: pv.position.x + pv.velocity.x,
            y: pv.position.y + pv.velocity.y,
            z: pv.position.z + pv.velocity.z,
        },
        gstime(now.add(1, 'second').toDate()) // be sure to use a time 1 second later, since velocity is km/s
    );
    const ecfVelocity = { // subtract original ecf from ecfMoved to obtain velocity in ecf
        x: ecfMoved.x - ecf.x,
        y: ecfMoved.y - ecf.y,
        z: ecfMoved.z - ecf.z,
    };
}
```

**Comment by thkruz** [comment]
Slick idea. That should actually account for the rotation of the earth perfectly. Feels super obvious now that you post it - thanks for helping out!
