### ISSUE TITLE
Efficient way to get passes for a given coordinate on the Earth and a satellite

### ISSUE THREAD

**Issue by laptopdude90** [shashwatak/satellite-js#27]
Is there any built in method that will give me pass information, given a point on the Earth and a satellite object? Currently, I'm looping through from now until a week from now, 30 seconds at a time, checking the lookAngle elevation against a minimum angle.

**Comment by shashwatak** [comment]
I do not have a helper function that does that, but if you would like to make a pull request to include something useful like that (or other useful helper utilities you might have), I'd be happy to look over them and see if I can include them :)

**Comment by fpfaffendorf** [comment]
@laptopdude90 I'm facing the same challenge. Did you find or develop a better way ?

**Comment by laptopdude90** [comment]
@fpfaffendorf No, but I came up with an idea in theory:

Get the angle for two times, far apart, but less than an orbit period. I have a feeling they follow a sinusoidal trend (Not tested) so you could use that to narrow it down a lot, and then find the exact values and verify.

**Comment by fpfaffendorf** [comment]
@laptopdude90 Thanks for your response. That's an interesting idea that might save some CPU. Specially for LEO satellites.
I think that most satellite prediction software use different formulas to find the rise, transit and set times of a satellite instead of running the math for each instant. I've done that in the past for solar system objects and again, there were formulas. It wasn't necessary to loop.
Best,

**Comment by christianreyes** [comment]
I use this: https://github.com/nsat/jspredict

**Comment by thkruz** [comment]
jspredict looks very handy, but it still relies on looping through at a specified interval. 

What I have done to increase performance is throw a binary flag each iteration if the object is in view and if it is false, then check if it was true last iteration (determine if the object just left field of view).

If the object has just left field of view, I skip a number of iterations equal to 3/4th the period of the object (no way it is in view on the other side of the earth).

Example:

At 1200z the ISS comes into field of view. I check at 1201z, 1202z, 1203z and 1204z and it is still in view. At 1205z it is out of view, so instead of adding 60s, I add ~67 minutes (75% of its 90 minute orbital period) and then continue iterating at 60s intervals.

Since I often want 1s intervals this can save me hundreds of thousands of iterations.

**Comment by thkruz** [comment]
This can probably be closed.
