### ISSUE TITLE
Getting perigee, apogee and orbital speed in km/s?

### ISSUE THREAD

**Issue by pkrasicki** [shashwatak/satellite-js#57]
Is it possible to get this information directly from satellite.js?

**Comment by pkrasicki** [comment]
I've noticed they are already calculated internally, but don't seem to be exposed to the user. Exposing parsed information from the TLE (mean motion etc.) would be useful too, so that users wouldn't have to parse TLE themselves.

**Comment by thkruz** [comment]
Looks like this was solved and can be closed?

**Comment by ezze** [comment]
Not sure that we will add some new [transform functions](https://github.com/shashwatak/satellite-js#coordinate-transforms). At least, I won't take that responsibility. AFAIK, these functions are not part of `sgp4` and were introduced by @shashwatak. We should ask him to review and decide whether to add them but I'm not sure he is on the party. :)

If anybody feel lucky and confident for further library maintenance then just ask me and welcome! :tada:

**Comment by pkrasicki** [comment]
I was hoping this library would grow to do more things than just sgp4. There are libraries like that for Python, but none for JavaScript.

**Comment by ezze** [comment]
@pkrasicki, there is no person who can make this library grow at the moment. It seems that @shashwatak doesn't support it anymore. I don't have enough knowledges in order to make significant changes to the library, and my mission was to make it friendly to modern environments such as ES6/Node.js and setup CI for automated testing. Moreover, I'm busy at work like most of you, and there is no free time to contribute to open source projects seriously.

Luckily, I have administrative privileges to push commits to Github and publish packages to npm, so hope, as I already said, I'm ready to share them with a person who is very interested in supporting the library.
