### ISSUE TITLE
Can I use satellite-js to create czml files?

### ISSUE THREAD

**Issue by BaiH-ang** [shashwatak/satellite-js#77]
I don’t know how to create a simple satellite trajectory.
Can we get its trajectory by some formula instead of listing it？

**Comment by thkruz** [comment]
SGP4 IS the "simple" equation for figuring out a satellites position/velocity in space at a given time. There are more accurate (and complicated) methods for doing those calculations.

**Comment by BaiH-ang** [comment]
> SGP4 IS the "simple" equation for figuring out a satellites position/velocity in space at a given time. There are more accurate (and complicated) methods for doing those calculations.
thank you,can I use satellite-js to create czml files?

**Comment by BaiH-ang** [comment]
> SGP4 IS the "simple" equation for figuring out a satellites position/velocity in space at a given time. There are more accurate (and complicated) methods for doing those calculations.

I mean, is it possible to get a series of position and time coordinates by formula？please

**Comment by thkruz** [comment]
You can just use a simple for loop to accomplish that:

`
// Sample TLE
var tleLine1 = '1 25544U 98067A   19156.50900463  .00003075  00000-0  59442-4 0  9992',
      tleLine2 = '2 25544  51.6433  59.2583 0008217  16.4489 347.6017 15.51174618173442';    

// Initialize a satellite record
var satrec = satellite.twoline2satrec(tleLine1, tleLine2);

let realTime = new Date();
let listOfTimes = [];
let listOfPositions = [];

for (let i=0; i < 1440; i++;) {

// Calculate position and velocity
// Use the current time and add 1 minute each loop (1000 milliseconds * 60 seconds)
let propagationTime = realTime + (i * 1000 * 60);
var positionAndVelocity = satellite.propagate(satrec, propagationTime);
listOfTimes.push(propagationTime);
listOfPositions.push(positionAndVelocity);
}
`

**Comment by ezze** [comment]
@BaiH-ang Sorry, I'm late to the party but hope that I can add more light to answer your question as I have some little experience creating CZMLs with `satellite.js`.

@thkruz is right, `satellite.js` doesn't provide a magic function to create a CZML for Cesium but if you are familiar with [CZML specs](https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/CZML-Guide) it should be quite easy to make position calculations treating a satellite as a [Billboard](https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/Billboard).

![Screenshot_20210112_225045](https://user-images.githubusercontent.com/665479/104365194-c1003080-5528-11eb-92ec-71f48e4c83f8.png)

Unfortunatelly, I can't share the exact source code but can give an example of generated CZML and some hints on how it can be implemented by your own.

Just extract `aqua.czml` from [zip archive](https://github.com/shashwatak/satellite-js/files/5804588/aqua.czml.zip) and drag'n'drop it to [Cesium Viewer](https://cesium.com/cesiumjs/cesium-viewer/) to see it in action.

At the begining I was creating CZMLs on a server side with Node.js but this approach introduces an additional workload you really can avoid. Thanks to [web workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) all calculations are possible on a client side. Cesium has its own set of [web workers](https://github.com/CesiumGS/cesium/tree/master/Source/WorkersES6) which are started with [TaskProcessor](https://cesium.com/docs/cesiumjs-ref-doc/TaskProcessor.html). There are no obstacles to [write your own web worker](https://cesium.com/docs/cesiumjs-ref-doc/createTaskProcessorWorker.html) and run it in the same way. Before version 1.63 Cesium source code including web workers has been organized as AMD modules so it was tricky to prepare a proper worker file with [Require.js](https://requirejs.org/) and [Almond](https://github.com/requirejs/almond). But now it's [ported to ES6+](https://cesium.com/blog/2019/10/31/cesiumjs-es6/) and you can copy your own implementation of web worker to Cesium `Workers` directory. This is how I do it with [webpack](https://webpack.js.org/) and [copy-webpack-plugin](https://webpack.js.org/plugins/copy-webpack-plugin/):

```javascript
import CopyPlugin from 'copy-webpack-plugin';

const srcDirPath = path.resolve(__dirname, 'src');
const distDirPath = path.resolve(__dirname, 'dist');
const nodeModulesDirPath = path.resolve(__dirname, 'node_modules');

const { cesiumBundle } = process.env;

export default((env, argv) => {
  const { mode = 'development' } = argv;

  const cesiumDirName = `Cesium${mode === 'production' ? '' : 'Unminified'}`;
  const cesiumDirPath = path.resolve(nodeModulesDirPath, `cesium/Build/${cesiumDirName}`);

  const copyPluginPatterns = [];
  if (cesiumBundle) {
    Array.prototype.push.apply(copyPluginPatterns, ['Workers', 'ThirdParty', 'Assets', 'Widgets'].map(dirName => {
      return { from: `${cesiumDirPath}/${dirName}`, to: path.resolve(distDirPath, `cesium/${dirName}`) };
    }));
  }
  else {
    copyPluginPatterns.push({ from: cesiumDirPath, to: path.resolve(distDirPath, 'cesium') });
  }

  copyPluginPatterns.push({
    from: path.resolve(nodeModulesDirPath, '@geoapps/cesium-czml-orbit-worker/dist/czmlOrbitWorker.js'),
    to: path.resolve(distDirPath, 'cesium/Workers/czmlOrbitWorker.js')
  });

  // Other configuration preparations go here
  // ..........

  return {
    // Webpack configuration
    // ..........
    externals: cesiumBundle ? {} : { cesium: 'Cesium' },
    plugins: [
      // Many plugins here
      // ..........
      new CopyPlugin({ patterns: copyPluginPatterns })
    ]
  }
});
```

If environment variable `cesiumBundle` is set then Cesium itself become a part of your app bundle and you need to copy only `Workers` directory to `dist/cesium` (and some others if you really need them), e.g.:

```
cesiumBundle=yes webpack --mode=production --progress
```

Otherwise prebuilt version of Cesium will be copied to `dist/cesium`, you have to include it in your [html template](https://webpack.js.org/plugins/html-webpack-plugin/) manually and let Webpack to know in `externals` that when importing `cesium` it should look for global `Cesium` object to resolve it.

For both cases one should also copy custom ES5 compatible web workers (`czmlOrbitWorker.js` in the example) to `dist/cesium/Workers` directory or transpile them from ES6 to ES5 with additional Webpack [entry point](https://webpack.js.org/concepts/entry-points/).

Having such preparations now you are able to make satellite position calculations asynchronously and do not block your app's [event loop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop).

**app.js**

```javascript
import { TaskProcessor, CzmlDataSource } from 'cesium';

function async createSatelliteCzml(options) {
  const orbitTaskProcessor = new TaskProcessor('czmlOrbitWorker', 4);
  const czml = await orbitTaskProcessor.scheduleTask(options);
  const czmlDataSource = new CzmlDataSource();
  await czmlDataSource.process(czml);
  return czmlDataSource;
}

createSatelliteCzml({ id: 27424, startTime: new Date(), duration: 86400 }).catch(e => console.error(e));
```

**czmlOrbitWorker.js**

```javascript
import createTaskProcessorWorker from 'cesium/Source/WorkersES6/createTaskProcessorWorker';
import { twoline2satrec } from 'satellite.js';

function czmlOrbitWorker(options) {
  try {
    // Calculate satellite positions and prepare czml satellite packet based on input options
    // ..........
    return [
      { id: 'document', 'version': '1.0' },
      satellitePacket
    ]
  }
  catch (e) {
    console.error(e);
    throw e;
  }
}

export default createTaskProcessorWorker(czmlOrbitWorker);
```

Please note that you can update existing `CzmlDataSource` with its `process` method scheduling different worker tasks in a time. But in this case you have to store and extend existing [Availability](https://github.com/AnalyticalGraphicsInc/czml-writer/wiki/CZML-Structure#availability) time intervals for each new czml packet portion otherwise satellite positions from previous calculation tasks will be lost.

Here is a couple of video links demostrating how I've used it in my projects:

- https://www.youtube.com/watch?v=I8-vmpF86-Q
- https://www.youtube.com/watch?v=pA-LJszq2mQ
