### ISSUE TITLE
Getting lat/lon for a whole day.

### ISSUE THREAD

**Issue by JaniniRami07** [shashwatak/satellite-js#83]
Hey, I was trying to generate a list containing the lat/lon of the ISS in every second (preferably millisecond) of the day, I tried to do this and ended up crashing my browser, is there any efficient way to do so without crashing my browser?

```
function predPoints(tle1, tle2){
  var dateTime = new Date();
  var i;
  for (i = 0; i < 86401; i++){
    var satrec = satellite.twoline2satrec(tle1, tle2);

    var positionAndVelocity = satellite.propagate(satrec, dateTime.setSeconds(dateTime.getSeconds() + i ));
    var positionEci = positionAndVelocity.position;

    var gmst = satellite.gstime( dateTime.setSeconds(dateTime.getSeconds() + i ));

    var positionGd = satellite.eciToGeodetic(positionEci, gmst);

    var longitude = positionGd.longitude,
        latitude  = positionGd.latitude;

    var longitudeStr = satellite.degreesLong(longitude),
        latitudeStr  = satellite.degreesLat(latitude);

    position = [longitudeStr, latitude]
    console.log(position);
  }
```

**Comment by davidcalhoun** [comment]
It sounds like there's a problem in your code that is causing an infinite loop.  Double check the stop condition and make sure it is indeed exiting.  I'm using a loop strategy with my own library and it works fine and is very fast.

One second intervals will get you a pretty nice ground track, except at extreme polar latitudes on Mercator projection maps, which have more map distortion and need <1s intervals for a slightly smoother-looking line at those latitudes.

**Comment by thkruz** [comment]
I regularly do the whole catalog on a one second loop, so I agree with @davidcalhoun that your issue is that it isn't exiting. If you post your current code then I'd be happy to take a look.

I'd recommend interpolating between 250 or 500 millisecond measurements if you really want that level of detail - but as was said, you probably don't need that except in really specific cases. What are you trying to accomplish?

**Comment by JaniniRami07** [comment]
I just edited my issue and added the code I am working with.

**Comment by JaniniRami07** [comment]
@thkruz I am trying to get a list of lat/lon for the ISS throughout the day to plot them on a map creating a ground track look alike map.

**Comment by thkruz** [comment]
Two things that jump out (I can do some more testing when I get home):

Comment out the console.log and try again. You should instead do something like this:

Put this outside the loop.
```js
var positionArray = [];
```

And this at the bottom
```js
positionArray.push(position);
}

console.log(positionArray)
```

Second, lesser thing, is that having the var statements INSIDE the loop is going to cause new objects to be created every time. I would declare all your variables at the top ie:

```js
var positionAndVelocity, positionEci, ... etc
```

and the just change the values inside the loop so that it reuses those objects over and over.

**Comment by thkruz** [comment]
> @thkruz I am trying to get a list of lat/lon for the ISS throughout the day to plot them on a map creating a ground track look alike map.

Then @davidcalhoun is definitely correct that you do not need millisecond intervals. Try 500 milliseconds and see if you like the results. A more complete solution would change i to increment by 1000 unless the current latitude > 80 || < -80 and then increment by 250.

**Comment by JaniniRami07** [comment]
Thank you so much, removing the vars and declaring them outside the function made it work, Also thanks for the advice I will try use milliseconds instead of seconds and see how they compare in accuracy!
